### ISSUE TITLE
Failed to validate required field

### ISSUE THREAD

**Issue by boyeoffice** [BuildForSDG/Expert-System-for-Connecting-Qualified-Teachers-To-Schools-WebApi-#6]
Laravel request validation is not working, I created two different validation but refused to validate required field
![Screenshot from 2020-05-30 07-29-47](https://user-images.githubusercontent.com/25820415/83321514-380de080-a248-11ea-8cfa-ba21e41aaef1.png)

**Comment by richardiyama** [comment]
Fixed!!
